In [1]:
import torch

In [2]:
torch.empty(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
x=torch.rand(5,3)
x

tensor([[1.8124e-01, 1.7372e-01, 8.8426e-01],
        [7.0991e-02, 8.1688e-01, 6.4474e-04],
        [6.7352e-01, 4.2312e-01, 5.0937e-01],
        [1.1247e-01, 7.3703e-01, 2.0531e-01],
        [2.6724e-01, 4.7442e-01, 2.9229e-01]])

In [9]:
x=torch.zeros(5,3,dtype=torch.long).long()

In [13]:
x=torch.tensor([5.5,3])

In [14]:
x

tensor([5.5000, 3.0000])

In [15]:
x.dtype

torch.float32

In [16]:
y=torch.rand_like(x,dtype=torch.float32)

In [17]:
y

tensor([0.7418, 0.1257])

In [19]:
y.shape

torch.Size([2])

torch.float32

In [20]:
y=torch.ones(5,3)


In [21]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
x=torch.randn(5,3)
x

tensor([[-0.1373,  0.0253,  0.3063],
        [-0.4329, -1.2365,  0.4312],
        [-0.9010, -0.6585,  1.0662],
        [ 0.6886,  0.6322,  0.6858],
        [-2.0879, -0.7191,  0.2793]])

In [23]:
torch.add(x,y)

tensor([[ 0.8627,  1.0253,  1.3063],
        [ 0.5671, -0.2365,  1.4312],
        [ 0.0990,  0.3415,  2.0662],
        [ 1.6886,  1.6322,  1.6858],
        [-1.0879,  0.2809,  1.2793]])

In [24]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
y.add_(x)

tensor([[ 0.8627,  1.0253,  1.3063],
        [ 0.5671, -0.2365,  1.4312],
        [ 0.0990,  0.3415,  2.0662],
        [ 1.6886,  1.6322,  1.6858],
        [-1.0879,  0.2809,  1.2793]])

In [26]:
y

tensor([[ 0.8627,  1.0253,  1.3063],
        [ 0.5671, -0.2365,  1.4312],
        [ 0.0990,  0.3415,  2.0662],
        [ 1.6886,  1.6322,  1.6858],
        [-1.0879,  0.2809,  1.2793]])

In [30]:
x=torch.randn(4,3)
y=x.view(2,6)
y
x

tensor([[ 0.7495, -0.9353,  1.0885],
        [-0.3263,  0.2428, -0.3949],
        [ 0.9601,  1.3663, -0.1376],
        [ 0.1810,  1.3442,  1.1668]])

In [31]:
y

tensor([[ 0.7495, -0.9353,  1.0885, -0.3263,  0.2428, -0.3949],
        [ 0.9601,  1.3663, -0.1376,  0.1810,  1.3442,  1.1668]])

In [32]:
z=torch.randn(1)
z

tensor([-1.4007])

In [33]:
z.item()

-1.4007254838943481

In [34]:
a=torch.ones(5)

In [35]:
a

tensor([1., 1., 1., 1., 1.])

In [36]:
b=a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [37]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [40]:
a=np.add(a,1,out=a)
a

array([3., 3., 3., 3., 3.])

In [41]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [42]:
torch.cuda.is_available()

False

In [44]:
torch.cuda.is_available()

False

In [1]:
torch.cuda.is_avaliable()

NameError: name 'torch' is not defined

In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [6]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    x=torch.randn(4,3)
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([[ 1.6505,  1.8267,  0.5003],
        [ 0.7834,  0.5958, -0.3488],
        [-0.0291, -0.0820, -0.8761],
        [ 1.1949,  0.6586,  0.3184]], device='cuda:0')
tensor([[ 1.6505,  1.8267,  0.5003],
        [ 0.7834,  0.5958, -0.3488],
        [-0.0291, -0.0820, -0.8761],
        [ 1.1949,  0.6586,  0.3184]], dtype=torch.float64)


In [7]:
y.to("cpu").data.numpy()
y.cpu().data.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [15]:




#64个输入，每个1000维，中间层100维，输出10维
N,D_in,H,D_out=64,1000,100,10
#创建一些训练数据
import numpy as np
x=np.random.randn(N,D_in)
y=np.random.randn(N,D_out)
w1=np.random.randn(D_in,H)
w2=np.random.randn(H,D_out)
learning_rate=1e-6
for it in range(500):
    #Forward Pass:
    h=x.dot(w1) #N*H
    h_relu=np.maximum(h,0) #N*H
    y_pred=h_relu.dot(w2) #N*D_out
    
    #Compute Loss
    loss=np.square(y_pred-y).sum()
    print(it,loss)
    
    #Backward Pass
    #Compute the Gradient
    grad_y_pred=2*(y_pred-y)
    grad_w2=h_relu.T.dot(grad_y_pred)
    grad_h_relu=grad_y_pred.dot(w2.T)
    grad_h=grad_h_relu.copy()
    grad_h[h<0]=0
    grad_w1=x.T.dot(grad_h)
    
    #update weights of w1 and w2
    w1-=learning_rate*grad_w1
    w2-=learning_rate*grad_w2
    

0 31053924.21200189
1 28851525.35936111
2 29396207.971677624
3 27910244.195483953
4 23055830.451406255
5 15754244.466170829
6 9384929.736840878
7 5167105.857660965
8 2911401.6635477096
9 1773038.7130996564
10 1198845.8236746907
11 886077.130706593
12 697206.7502490382
13 570074.2939222548
14 477086.83683552523
15 404901.1487631009
16 346735.9702381576
17 298856.63617669325
18 258900.75324489665
19 225220.28759178217
20 196704.5699266166
21 172402.72581227298
22 151596.10411707827
23 133666.1154072694
24 118165.56930024322
25 104732.24658967323
26 93042.93303967513
27 82843.23337506849
28 73915.1235394813
29 66093.90642046857
30 59211.659242230045
31 53143.65172365893
32 47786.2715992272
33 43044.25767488338
34 38840.89550253667
35 35109.41475940775
36 31784.15413437268
37 28820.245783067905
38 26170.98869727471
39 23796.927033816955
40 21666.897306565614
41 19744.40133056131
42 18015.868503694095
43 16458.59002712676
44 15055.542102861233
45 13788.664129444456
46 12641.967561022713
47 

494 9.791915589968246e-06
495 9.39515466527554e-06
496 9.01442923899578e-06
497 8.649149923369151e-06
498 8.298774545116965e-06
499 7.962468835752972e-06


In [16]:
x

array([[-2.45213308, -0.94139495,  1.36180289, ..., -0.64700185,
         0.33320385, -0.16688306],
       [-0.46407337,  0.10500622,  1.48286085, ...,  0.97102688,
         0.71117799, -1.19072792],
       [ 0.41769416,  1.73887583,  1.47666243, ...,  0.48039547,
        -0.12351727, -1.45837967],
       ...,
       [-0.82786291,  1.52546985,  0.3557264 , ..., -0.10774192,
        -0.17013574, -0.61749026],
       [ 0.63890087,  0.87602237, -0.81924885, ...,  0.45784991,
        -0.79473961, -2.15446108],
       [ 1.39028816,  0.50868101, -0.42835726, ..., -0.81100889,
        -1.09927817,  0.11184302]])

In [17]:
 y_pred

array([[-3.36350699,  2.67042499, -1.26356804, -0.67571422,  0.29786081,
        -0.67167667, -0.086541  ,  0.30896239, -0.80362936,  0.02726322],
       [ 0.61469341, -1.260017  , -0.08257745,  0.48333223,  2.07063602,
        -0.18493382,  0.27244763,  0.7555936 , -0.42734166, -0.06245151],
       [ 0.21914299, -0.92184522,  1.75355657,  0.02360061, -2.29641949,
         2.3785472 ,  0.35566929, -0.93924847,  0.07531497,  0.06205455],
       [ 1.02943197, -0.78557176, -0.82125563,  0.02445958,  0.95604955,
         0.77755935,  0.14314721,  0.60736982,  0.40610393,  1.31986635],
       [ 0.1877065 , -1.13211815, -2.04923376, -0.01809357, -0.71405542,
         1.43789748,  1.372441  ,  0.11384168,  0.05816208,  1.64177524],
       [ 2.46433321, -0.25725561, -1.2719861 , -0.08108763, -0.64441752,
         0.3583539 ,  1.24554706,  0.28523038,  0.08234547, -1.65729776],
       [ 0.15164177,  2.39107249,  1.53394657, -0.51876347, -1.11545092,
         0.04779561,  0.1191181 , -1.4538153 

In [18]:
y

array([[-3.36353013,  2.67044442, -1.26348904, -0.67571258,  0.29788026,
        -0.67169583, -0.08657653,  0.30891684, -0.80362257,  0.02719771],
       [ 0.61470054, -1.26002955, -0.08261049,  0.48331872,  2.07064036,
        -0.18492808,  0.27244794,  0.75560363, -0.42734873, -0.06241888],
       [ 0.2192031 , -0.92185105,  1.75337243,  0.02358046, -2.29641636,
         2.3786121 ,  0.35570817, -0.93914693,  0.07528637,  0.06216001],
       [ 1.02944067, -0.78557489, -0.82129367,  0.02445976,  0.95603169,
         0.77756897,  0.14315136,  0.6074041 ,  0.40609183,  1.31988775],
       [ 0.18771528, -1.13212076, -2.04928697, -0.01810309, -0.71403033,
         1.43790857,  1.3724593 ,  0.11387479,  0.058156  ,  1.64178707],
       [ 2.46434619, -0.25726101, -1.27207883, -0.08108835, -0.64441804,
         0.35837047,  1.24557515,  0.28526896,  0.08235214, -1.65725848],
       [ 0.15156942,  2.39109382,  1.53412022, -0.51874399, -1.11543429,
         0.04771328,  0.11905611, -1.4539515 

In [19]:
y_pred-y

array([[ 2.31360999e-05, -1.94331538e-05, -7.90027747e-05,
        -1.63807668e-06, -1.94536952e-05,  1.91603651e-05,
         3.55341583e-05,  4.55577885e-05, -6.79421237e-06,
         6.55170712e-05],
       [-7.13356981e-06,  1.25559147e-05,  3.30417655e-05,
         1.35048078e-05, -4.33984492e-06, -5.74041038e-06,
        -3.15408708e-07, -1.00269807e-05,  7.06545782e-06,
        -3.26235665e-05],
       [-6.01103425e-05,  5.82686202e-06,  1.84139357e-04,
         2.01569812e-05, -3.12658257e-06, -6.49052316e-05,
        -3.88845781e-05, -1.01545875e-04,  2.86047762e-05,
        -1.05458413e-04],
       [-8.69713928e-06,  3.13365228e-06,  3.80456266e-05,
        -1.80291327e-07,  1.78572729e-05, -9.62126929e-06,
        -4.15485528e-06, -3.42766604e-05,  1.21004318e-05,
        -2.13988179e-05],
       [-8.78147147e-06,  2.60917599e-06,  5.32135223e-05,
         9.51948134e-06, -2.50926297e-05, -1.10918607e-05,
        -1.83022266e-05, -3.31108280e-05,  6.08137669e-06,
        -1.